### ISSUE TITLE
Biomes O Plenty seems to be a dependency

### ISSUE THREAD

**Issue by mattstreet** [Ted80-Minecraft-Mods/Better-World-Generation-4#19]
C:\Users\sipm\Desktop\forge\src\bwg4\support\SupportBopHell.java
Error:(11, 55) java: package biomesoplenty.common.world does not exist
Error:(16, 55) java: package biomesoplenty.common.world does not exist

I really love that you've open sourced your code, I'm trying to use it as part of understanding world generation. Your documentation doesn't mention requiring Biomes O' Plenty to compile it but it seems to. I'm also not sure what version to use if it is required, since you've updated for 1.7 but BoP doesn't seem to have yet.

**Comment by ted80** [comment]
has been fixed
