### ISSUE TITLE
For transporting your mod to MCBBS

### ISSUE THREAD

**Issue by TehporP** [Ted80-Minecraft-Mods/Better-World-Generation-4#26]
Hello Ted Here is TehporP.
BWG4 is a amazing gen mod.
My player said it is really fun,
Because of GWF BWG4 isn't so popular in China
So I translated it into Chinese
And may I transport your mod to MCBBS？(A China MC forum)
I swear Chinese player will be crazy about your mod :)
I will sign your name on my post
and I will not make ANY money on it

**Comment by ted80** [comment]
sure as long as you don't make any money.

**Comment by TehporP** [comment]
Thanks！
