### ISSUE TITLE
BWG4 doesn't allow other biomes to spawn in "Default"

### ISSUE THREAD

**Issue by Wytchcat** [Ted80-Minecraft-Mods/Better-World-Generation-4#3]
Normally with BWG4 or BoP installed, creating a default world gives me a mishmash of default biomes and one or the others additional biomes.

With both installed I am only getting BWG4 added biomes in a default generation.

**Comment by ted80** [comment]
thats because there is no Biomes O Plenty support yet and do you mean default or better default?

**Comment by ted80** [comment]
they should spawn when better default is turned off

**Comment by ted80** [comment]
works with ExtraBiomesXL

**Comment by ted80** [comment]
works with Biomes O Plenty as well

**Comment by Wytchcat** [comment]
Well for the EBXL crowd that will be great.

But I'm dedicated to my BoP!  LOL.  Thanks for the update... I'm just too eager.
