### ISSUE TITLE
Ice over most ocean surface.

### ISSUE THREAD

**Issue by Wytchcat** [Ted80-Minecraft-Mods/Better-World-Generation-4#5]
![Uploading bwg4oceanbug.png . . .]()
I'll do this officially... too!  

MC 1.6.4
Forge 953
BWG4 1.1.9

I'm finding that there is ice over the majority of my ocean surface whether in an ice biome or not, on both client and server.

Server reports biome as ocean but...ICE. 

Reports of similar in forum:

"Hello guys,

I installed the version 1.1.8 and I noticed that bwg4 overwrites a minecraft biome.
the minecraft biome "Ocean" (ID 0) after installation turns to bwg4 biome "River_ice"
in the bwg4 configuration file can not find any biome with ID 0

Before:
0,Ocean,0.5,0.5,0.1,-1.0,0.4,WATER,net.minecraft.world.biome.BiomeGenOcean

After:
0,River_ice,0.0,0.5,0.1,-0.8,0.0,WATER,bwg4.biomes.BWG4BiomesDefault

Can anyone tell me why?

Thanks"

"Im not sure if its this mod that's causing this but for some reason ice river biomes are generating where ocean biomes should, leading to vast expanses of ice. It could be a biome id conflict though I think they are both vanilla biomes so they shouldn't conflict"

Thanks!

**Comment by Wytchcat** [comment]
Ok... that was vanilla only.. but when new world started with correct BWG4 world type out the gate, all oceans now read as "river_sand".

This also makes me cry... _sniff sniff_ <--- see tears and everything!

**Comment by duck1123** [comment]
If I start a new world in single player, it works fine. I loaded the multiverse plugin and loaded up a new world and still had the same issue.

Also using MCPC+

**Comment by skudster13** [comment]
MCPC+ also.  I'm getting the oceans of ice  :(

**Comment by Wytchcat** [comment]
You can cure the oceans of ice by making sure that you have BWG4 as your world type.  See the directions for doing this on a server in the first page readme.

Unfortunately you will then have no oceans but river_sand.  Ted80 assures me this will be cured in the next update.  But it won't be available for 1.6.4 so who knows how long that will be for servers.

**Comment by ted80** [comment]
this will be fixed in 1.7
